version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: Deploy Over SSH
          command: sudo sh deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
