version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - image: circleci/python:2.7-stretch
    working_directory: ~/repo
    steps:
      - checkout

      # BUILD - BACKEND
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            python install -r backend/requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ls -rlta
            cd ~/repo
            ls -rlta
            bash deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
