version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout

      # BUILD - BACKEND
      - run
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            python install -r requirements.txt
      - run
          name: Running tests
          command: |
            . venv/bin/activate
#      - run:
#          name: Greeting
#          command: echo Hello, world.
#      - run:
#          name: Print the Current Time
#          command: date
#      - run:
#          name: test script
#          command: |
#            pwd
#            ls -rlta
#            cd ~/repo
#            ls -rlta
#            bash deploy.sh
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ls -rlta
            cd ~/repo
            ls -rlta

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
